export enum QuestionCategory {
    TEAMWORK = "TEAMWORK",
    INITIATIVE = "INITIATIVE",
    PROFESSIONALISM = "PROFESSIONALISM",
    COMMUNICATION = "COMMUNICATION",
    TECHNICAL_SKILLS = "TECHNICAL_SKILL"
}